### ISSUE TITLE
Not receiving HTTP POST containing a JSON array Data in webhook url 

### ISSUE THREAD

**Issue by SantoshSKhavekar** [sendgrid/smtpapi-nodejs#78]
#### Issue Summary
Hi,

I tried to implement smtpapi API with setup of webhook but unfortunatly mails are delivering to users but data are not receiving intop webhook url.

Here is my code to send mails:-

```javascript
var smtpapi   = require('smtpapi');
var header    = new smtpapi();
header.addTo(email);									
header.setUniqueArgs({'unique_id': "123"});
var headers={'X-SMTPAPI':JSON.stringify(header)};
var settings  = {
	host:config.email_host_name,
	port:25
};
var smtpTransport1 = nodemailer.createTransport(settings);
var email="khavekarsan@gmail.com";
var subject="Test SMTPAPI";
var out="<b>Hello world</b>";
var mailOptions = {	
  to :email,	
  from:config.email_from_addr,
  subject :subject,					
  html:out,
  headers:  headers
};
smtpTransport1.sendMail(mailOptions, function(error, response) {
	if(error) {
		console.log("send mail error: "+error);							
	 }else {
		console.log("Message sent response:- "+util.format("%j",response));
	 }
});
```

I did setup webhook url as "https://npd.nowconfer.com:5000/calendar/sendgrid_webhook"  in mail settings page.
can you figure out what is happening wrong here?

**Comment by thinkingserious** [comment]
Hello @SantoshSKhavekar,

This library handles the sending of email through our SMTP API by helping you create the necessary headers. The webhook portion you describe falls outside of the scope of this library.

My suggestion is to try reaching out to the StackOverflow community. It will be important to describe the architecture of your webhook setup and provide an overview of the expected behavior along with any relevant code and configuration information.

I hope that helps!

With Best Regards,

Elmer
